### ISSUE TITLE
react-packager has encountered an internal error, please check your terminal error output for more details

### ISSUE THREAD

**Issue by ysq1051838264** [cssivision/react-native-qrcode#29]
Unable to download JS bundle
                                                                  com.facebook.react.devsupport.DebugServerException: The development server returned response error code: 500
                                                                  
                                                                  URL: http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false
                                                                  
                                                                  Body:
                                                                  {"type":"InternalError","message":"react-packager has encountered an internal error, please check your terminal error output for more details"}
                                                                      at com.facebook.react.devsupport.DevServerHelper$5.onResponse(DevServerHelper.java:323)
                                                                      at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
                                                                      at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                      at java.lang.Thread.run(Thread.java:818)

**Comment by ysq1051838264** [comment]
已经解决，重新构建。1:- close the Terminal. 2:- close the application in a device. And rebuild the application it will work.
