### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by hejunbinlan** [cssivision/react-native-qrcode#32]
Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:681:18)
    at Object.readSync (/Users/xxxx/workspace-js/ReactNative/HotCode/node_modules/graceful-fs/polyfills.js:138:28)
    at tryReadSync (fs.js:542:20)
    at Object.fs.readFileSync (fs.js:585:19)
    at Module._readSourceCode (/Users/xxxx/workspace-js/ReactNative/HotCode/node_modules/metro-bundler/build/node-haste/Module.js:205:29)
    at Module._getCacheProps (/Users/xxxx/workspace-js/ReactNative/HotCode/node_modules/metro-bundler/build/node-haste/Module.js:395:29)
    at Module._readFromTransformCache (/Users/xxxx/workspace-js/ReactNative/HotCode/node_modules/metro-bundler/build/node-haste/Module.js:345:29)
    at Module.readCached (/Users/xxxx/workspace-js/ReactNative/HotCode/node_modules/metro-bundler/build/node-haste/Module.js:332:19)
    at ResolutionRequest.preprocessModule (/Users/xxxx/workspace-js/ReactNative/HotCode/node_modules/metro-bundler/build/node-haste/DependencyGraph/ResolutionRequest.js:380:27)
    at ResolutionRequest._preprocessPotentialDependencies (/Users/xxxx/workspace-js/ReactNative/HotCode/node_modules/metro-bundler/build/node-haste/DependencyGraph/ResolutionRequest.js:364:27)

**Comment by DeforeChen** [comment]
I run into the same issue. Maybe the QR component does not match the later RN version? In my project, the RN version is 0.47 or later.

**Comment by zero1108** [comment]
I encountered the same issue too, my project's RN version is 0.47

**Comment by ssshen** [comment]
@zero1108 delete node_modeule ,and run ```npm install``` ,but the error still exist

**Comment by wangfaguo** [comment]
I encountered the same issue too, my project's RN version is 0.51

**Comment by holasebas** [comment]
same here, RN version 0.52, HELP!!!

**Comment by elijahmurray** [comment]
I was able to get past the error by running `npm install graceful-fs` explicitly within my project. Hope it helps!

**Comment by wkchen66** [comment]
Try end the project process on the device and restart(`react-native run-android`)

**Comment by buddudevelopers** [comment]
This happened when I moved the index.js file from the root of the project and it was resolved once I placed it back

**Comment by anggihseptiawan** [comment]
it works for me, https://stackoverflow.com/questions/66771543/metro-bundler-error-eisdir-illegal-operation-on-a-directory-read

**Comment by maxhudson** [comment]
This can happen when running from a non-ejected expo repository
